#**********************************************/
#* ██████╗ ███████╗███████╗████████╗███████╗  */
#* ██╔══██╗██╔════╝██╔════╝╚══██╔══╝██╔════╝  */
#* ██████╔╝█████╗  █████╗     ██║   ███████╗  */
#* ██╔══██╗██╔══╝  ██╔══╝     ██║   ╚════██║  */
#* ██████╔╝███████╗███████╗   ██║   ███████║  */
#* ╚═════╝ ╚══════╝╚══════╝   ╚═╝   ╚══════╝  */
#*                                            */
#**********************************************/


directory: ~/media/audio/music
library: ~/.local/share/beets/musiclibrary.db
import:
    move: yes
plugins: fetchart lyrics lastgenre edit
