/home/gian/music/alan_stivell/renaissance_of_the_celtic_harp/01_ys.mp3
/home/gian/music/alan_stivell/renaissance_of_the_celtic_harp/02_marv_pontkellec.mp3
/home/gian/music/alan_stivell/renaissance_of_the_celtic_harp/03_ap_huw_and_penllyn.mp3
/home/gian/music/alan_stivell/renaissance_of_the_celtic_harp/04_eliz_iza.mp3
/home/gian/music/alan_stivell/renaissance_of_the_celtic_harp/05_gaeltacht.mp3
/home/gian/music/alan_stivell/celtic_symphony/01_kelc_h_unan_first_circle.mp3
/home/gian/music/alan_stivell/celtic_symphony/02_kelc_h_daou_second_circle.mp3
/home/gian/music/alan_stivell/celtic_symphony/03_kelc_h_tri_third_circle.mp3
/home/gian/music/alan_stivell/au_dela_des_mots/01_la_harpe,_l_eau,_le_vent_1.mp3
/home/gian/music/alan_stivell/au_dela_des_mots/02_la_celtie_et_l_infini_1.mp3
/home/gian/music/alan_stivell/au_dela_des_mots/03_la_celtie_et_l_infini_2.mp3
/home/gian/music/alan_stivell/au_dela_des_mots/04_dihun_telenn_vmarzhin.mp3
/home/gian/music/alan_stivell/au_dela_des_mots/05_la_harpe_et_l_enfant.mp3
/home/gian/music/alan_stivell/au_dela_des_mots/06_bleimor,_le_bagad.mp3
/home/gian/music/alan_stivell/au_dela_des_mots/07_gourin-pontivy.mp3
/home/gian/music/alan_stivell/au_dela_des_mots/08_e_kreiz_breizh.mp3
/home/gian/music/alan_stivell/au_dela_des_mots/09_goltraidhe.mp3
/home/gian/music/alan_stivell/au_dela_des_mots/10_et_les_feuilles_repousseronta_.mp3
/home/gian/music/alan_stivell/au_dela_des_mots/11_demain_matin_chez_o_carolan.mp3
/home/gian/music/alan_stivell/au_dela_des_mots/12_harpe_atlantique-la_route_de_l_etain-.mp3
/home/gian/music/alan_stivell/au_dela_des_mots/13_la_celtie_et_l_infini_3.mp3
/home/gian/music/alan_stivell/au_dela_des_mots/14_la_harpe,_l_eau,_le_vent_2.mp3
/home/gian/music/bill_evans_and_jim_hall/undercurrent/01_my_funny_valentine.flac
/home/gian/music/bill_evans_and_jim_hall/undercurrent/02_i_hear_a_rhapsody.flac
/home/gian/music/bill_evans_and_jim_hall/undercurrent/03_dream_gypsy.flac
/home/gian/music/bill_evans_and_jim_hall/undercurrent/04_romain.flac
/home/gian/music/bill_evans_and_jim_hall/undercurrent/05_skating_in_central_park.flac
/home/gian/music/bill_evans_and_jim_hall/undercurrent/06_darn_that_dream.flac
/home/gian/music/bill_evans_and_jim_hall/undercurrent/07_stairway_to_the_stars.flac
/home/gian/music/bill_evans_and_jim_hall/undercurrent/08_i_m_getting_sentimental_over_you.flac
/home/gian/music/bill_evans_and_jim_hall/undercurrent/09_my_funny_valentine-alternate_take-.flac
/home/gian/music/bill_evans_and_jim_hall/undercurrent/10_romain-alternate_take-.flac
/home/gian/music/brain.fm/focus/04_focus.mp3
/home/gian/music/brain.fm/focus/05_focus.mp3
/home/gian/music/brain.fm/focus/06_focus.mp3
/home/gian/music/brain.fm/focus/02_forest_1.mp3
/home/gian/music/brain.fm/focus/01_atmospheric_focus_1.mp3
/home/gian/music/johann_sebastian_bach/the_very_best_of_bach/01_toccata_and_fugue_in_d_minor,_bwv_565_toccata.mp3
/home/gian/music/johann_sebastian_bach/the_very_best_of_bach/02_orchestral_suite_no._2_in_b_minor,_bwv_1067_vii._badinerie.mp3
/home/gian/music/johann_sebastian_bach/the_very_best_of_bach/03_concerto_for_2_violins_in_d_minor,_bwv_1043_ii._largo_ma_non_tanto.mp3
/home/gian/music/johann_sebastian_bach/the_very_best_of_bach/04_mass_in_b_minor,_bwv_232_agnus_dei.mp3
/home/gian/music/johann_sebastian_bach/the_very_best_of_bach/05_herz_und_mund_und_tat_und_leben,_bwv_147_x._jesu,_joy_of_man_s_desiring-arr._m._hess-.mp3
/home/gian/music/johann_sebastian_bach/the_very_best_of_bach/06_weichet_nur,_betubte_schatten,_bwv_202,_wedding_cantata_i._adagio.mp3
/home/gian/music/johann_sebastian_bach/the_very_best_of_bach/07_concerto_for_violin_and_oboe_in_c_minor,_bwv_1060_ii._adagio.mp3
/home/gian/music/johann_sebastian_bach/the_very_best_of_bach/08_wachet_auf,_ruft_uns_die_stimme,_bwv_140.mp3
/home/gian/music/johann_sebastian_bach/the_very_best_of_bach/09_violin_partita_no._3_in_e_major,_bwv_1006_i._preludio.mp3
/home/gian/music/johann_sebastian_bach/the_very_best_of_bach/10_st._matthew_passion,_bwv_244_erbarme_dich,_mein_gott.mp3
/home/gian/music/johann_sebastian_bach/the_very_best_of_bach/11_brandenburg_concerto_no._4_in_g_major,_bwv_1049_i._allegro.mp3
/home/gian/music/johann_sebastian_bach/the_very_best_of_bach/12_the_well-tempered_clavier,_book_i_prelude_and_fugue_no._1_in_c_major,_bwv_846.mp3
/home/gian/music/johann_sebastian_bach/the_very_best_of_bach/13_orchestral_suite_no._3_in_d_major,_bwv_1068_ii._air_on_a_g_string.mp3
/home/gian/music/johann_sebastian_bach/the_very_best_of_bach/14_goldberg_variations,_bwv_988_i._aria.mp3
/home/gian/music/johann_sebastian_bach/the_very_best_of_bach/15_cello_suite_no._1_in_g_major,_bwv_1007_i._prelude.mp3
/home/gian/music/johann_sebastian_bach/the_very_best_of_bach/16_cello_suite_no._1_in_g_major,_bwv_1007_vii._gigue.mp3
/home/gian/music/johann_sebastian_bach/the_very_best_of_bach/17_brandenburg_concerto_no._3_in_g_major,_bwv_1048_iii._allegro.mp3
/home/gian/music/johann_sebastian_bach/the_very_best_of_bach/18_anna_magdalena_notenbuch_in_g_major,_bwv_anh._114_minuet.mp3
/home/gian/music/johann_sebastian_bach/the_very_best_of_bach/19_st._matthew_passion,_bwv_244_o_haupt_voll_blut_und_wunden.mp3
/home/gian/music/johann_sebastian_bach/the_very_best_of_bach/20_oboe_concerto_in_g_minor,_bwv_1056_ii._largo.mp3
/home/gian/music/johann_sebastian_bach/the_very_best_of_bach/21_harpsichord_concerto_no._1_in_d_minor,_bwv_1052_i._allegro.mp3
/home/gian/music/johann_sebastian_bach/the_very_best_of_bach/22_cantata_no._82,_bwv_82_ich_habe_genug_iii._schlummert_ein.mp3
/home/gian/music/johann_sebastian_bach/the_very_best_of_bach/23_italian_concerto,_bwv_971_i._allegro.mp3
/home/gian/music/johann_sebastian_bach/the_very_best_of_bach/24_magnificat_in_d_major,_bwv_243_magnificat.mp3
/home/gian/music/johann_sebastian_bach/the_very_best_of_bach/25_violin_concerto_no._1_in_a_minor,_bwv_1041_iii._allegro_assai.mp3
/home/gian/music/johann_sebastian_bach/the_very_best_of_bach/26_brandenburg_concerto_no._5_in_d_major,_bwv_1050_iii._allegro.mp3
/home/gian/music/johann_sebastian_bach/the_very_best_of_bach/27_christmas_oratorio,_bwv_248_jauchzet,_frohlocket.mp3
/home/gian/music/john_coltrane/giant_steps/01_giant_steps.m4a
/home/gian/music/john_coltrane/giant_steps/02_cousin_mary.m4a
/home/gian/music/john_coltrane/giant_steps/03_countdown.m4a
/home/gian/music/john_coltrane/giant_steps/04_spiral.m4a
/home/gian/music/john_coltrane/giant_steps/05_syeeda_s_song_flute.m4a
/home/gian/music/john_coltrane/giant_steps/06_naima.m4a
/home/gian/music/john_coltrane/giant_steps/07_mr._p.c_.m4a
/home/gian/music/john_coltrane/giant_steps/08_giant_steps-alternate_take-.m4a
/home/gian/music/john_coltrane/giant_steps/09_naima-alternate_take-.m4a
/home/gian/music/john_coltrane/giant_steps/10_cousin_mary-alternate_take-.m4a
/home/gian/music/john_coltrane/giant_steps/11_countdown-alternate_take-.m4a
/home/gian/music/john_coltrane/giant_steps/12_syeeda_s_song_flute-alternate_take-.m4a
/home/gian/music/john_coltrane/impressions/01_india.m4a
/home/gian/music/john_coltrane/impressions/02_up_gainst_the_wall.m4a
/home/gian/music/john_coltrane/impressions/03_impressions.m4a
/home/gian/music/john_coltrane/impressions/04_after_the_rain.m4a
/home/gian/music/john_coltrane/ola_copy_coltrane/01_ola_copy_.m4a
/home/gian/music/john_coltrane/ola_copy_coltrane/02_dahomey_dance.m4a
/home/gian/music/john_coltrane/ola_copy_coltrane/03_aisha.m4a
/home/gian/music/john_coltrane/ola_copy_coltrane/04-original_untitled_ballad_to_her_ladyship-.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/01_tenor_madness.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/02_weeja.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/03_polka_dots_and_moonbeams.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/04_on_it.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/05_avalon.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/06_tenor_conclave.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/07_how_deep_is_the_ocean_.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/08_just_you,_just_me.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/09_bob_s_boys.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/10_mating_call.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/11_soultrane.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/12_gnid.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/13_super_jet.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/14_on_a_misty_night.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/15_romas.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/16_soul_eyes.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/17_anatomy.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/18_interplay.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/19_light_blue.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/20_c.t.a_.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/21_eclypso.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/22_solacium.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/23_minor_mishap.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/24_tommy_s_time.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/25_dakar.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/26_mary_s_blues.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/27_route_4.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/28_velvet_scene.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/29_witches_pit.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/30_cat_walk.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/31_pot_pourri.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/32_j.m._s_dream_doll.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/33_don_t_explain.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/34_falling_in_love_with_love.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/35_blue_calypso.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/36_the_way_you_look_tonight.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/37_from_this_moment_on.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/38_one_by_one.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/39_cattin_.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/40_anatomy.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/41_vodka.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/42_sunday.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/43_straight_street.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/44_while_my_lady_sleeps.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/45_chronic_blues.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/46_bakai.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/47_violets_for_your_furs.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/48_time_was.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/49_i_hear_a_rhapsody.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/50_trane_s_slow_blues.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/51_slowtrane.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/52_like_someone_in_love.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/53_i_love_you.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/54_dealin-take_1-.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/55_dealin-take_2-.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/56_wheelin-take_1-.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/57_wheelin-take_2-.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/58_robbins_nest.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/59_things_ain_t_what_they_used_to_be.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/60_you_leave_me_breathless.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/61_bass_blues.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/62_soft_lights_and_sweet_music.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/63_traneing_in.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/64_slow_dance.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/65_our_delight.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/66_they_can_t_take_that_away_from_me.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/67_woody_n_you.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/68_i_got_it_bad-and_that_ain_t_good-.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/69_undecided.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/70_soul_junction.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/71_what_is_there_to_say_.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/72_birk_s_works.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/73_hallelujah.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/74_all_morning_long.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/75_billie_s_bounce.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/76_solitude.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/77_two_bass_hit.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/78_soft_winds.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/79_lazy_mae.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/80_under_paris_skies.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/81_two_sons.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/82_clifford_s_kappa.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/83_filide.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/84_paul_s_pal.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/85_ammon_joy.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/86_groove_blues.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/87_the_real_mccoy.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/88_it_might_as_well_be_spring.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/89_lush_life.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/90_the_believer.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/91_nakatini_serenade.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/92_come_rain_or_come_shine.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/93_lover.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/94_russian_lullaby.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/95_theme_for_ernie.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/96_you_say_you_care.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/97_good_bait.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/98_i_want_to_talk_about_you.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/99_lyresto.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/100_why_was_i_born_.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/101_freight_trane.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/102_i_never_knew.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/103_big_paul.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/104_rise_n_shine.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/105_i_see_your_face_before_me.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/106_if_there_is_someone_lovelier_than_you.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/107_little_melonae.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/108_by_the_numbers.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/109_black_pearls.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/110_lover,_come_back_to_me.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/111_sweet_sapphire_blues.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/112_spring_is_here.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/113_invitation.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/114_i_m_a_dreamer,_aren_t_we_all.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/115_love_thy_neigbor.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/116_don_t_take_your_love_from_me.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/117_stardust.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/118_my_ideal.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/119_i_ll_get_by.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/120_do_i_love_you_because_you_re_beautiful_.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/121_then_i_ll_be_tired_of_you.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/122_something_i_dreamed_last_night.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/123_bahia.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/124_goldsboro_express.m4a
/home/gian/music/john_coltrane/the_prestige_recordings/125_time_after_time.m4a
/home/gian/music/john_coltrane/expression/01_ogunde.m4a
/home/gian/music/john_coltrane/expression/02_to_be.m4a
/home/gian/music/john_coltrane/expression/03_offering.m4a
/home/gian/music/john_coltrane/expression/04_expression.m4a
/home/gian/music/john_coltrane/expression/05_number_one.m4a
/home/gian/music/john_coltrane/coltrane/01_bakai.m4a
/home/gian/music/john_coltrane/coltrane/02_violets_for_your_furs.m4a
/home/gian/music/john_coltrane/coltrane/03_time_was.m4a
/home/gian/music/john_coltrane/coltrane/04_straight_street.m4a
/home/gian/music/john_coltrane/coltrane/05_while_my_lady_sleeps.m4a
/home/gian/music/john_coltrane/coltrane/06_chronic_blues.m4a
/home/gian/music/john_coltrane/blue_train/01_blue_train.mp3
/home/gian/music/john_coltrane/blue_train/02_moment_s_notice.mp3
/home/gian/music/john_coltrane/blue_train/03_locomotion.mp3
/home/gian/music/john_coltrane/blue_train/04_i_m_old_fashioned.mp3
/home/gian/music/john_coltrane/blue_train/05_lazy_bird.mp3
/home/gian/music/john_coltrane/blue_train/06_blue_train-alternate_take-.mp3
/home/gian/music/john_coltrane/blue_train/07_lazy_bird-alternate_take-.mp3
/home/gian/music/john_coltrane/a_love_supreme/01_part_1_acknowledgement.mp3
/home/gian/music/john_coltrane/a_love_supreme/02_part_2_resolution.mp3
/home/gian/music/john_coltrane/a_love_supreme/03_part_3_pursuance.mp3
/home/gian/music/john_coltrane/a_love_supreme/04_part_4_psalm.mp3
/home/gian/music/keith_jarrett/the_ka_pp_ln_concert/01_ka_pp_ln,_january_24,_1975,_part_i.flac
/home/gian/music/keith_jarrett/the_ka_pp_ln_concert/02_ka_pp_ln,_january_24,_1975,_part_iia.flac
/home/gian/music/keith_jarrett/the_ka_pp_ln_concert/03_ka_pp_ln,_january_24,_1975,_part_iib.flac
/home/gian/music/keith_jarrett/the_ka_pp_ln_concert/04_ka_pp_ln,_january_24,_1975,_part_iic.flac
/home/gian/music/miles_davis/what_i_say_volume_2/01_yesternow_part_3.flac
/home/gian/music/miles_davis/what_i_say_volume_2/02_funky_tonk.flac
/home/gian/music/miles_davis/what_i_say_volume_2/03_the_sanctuary_theme.flac
/home/gian/music/miles_davis/what_i_say_volume_2/04_directions.flac
/home/gian/music/miles_davis/what_i_say_volume_2/05_honky_tonk.flac
/home/gian/music/miles_davis/what_i_say_volume_2/06_what_i_say_.flac
/home/gian/music/miles_davis/kind_of_blue/01_so_what.flac
/home/gian/music/miles_davis/kind_of_blue/02_freddie_freeloader.flac
/home/gian/music/miles_davis/kind_of_blue/03_blue_in_green.flac
/home/gian/music/miles_davis/kind_of_blue/04_all_blues.flac
/home/gian/music/miles_davis/kind_of_blue/05_flamenco_sketches.flac
/home/gian/music/miles_davis_featuring_keith_jarrett/what_i_say_volume_1/01_directions.flac
/home/gian/music/miles_davis_featuring_keith_jarrett/what_i_say_volume_1/02_honky_tonk.flac
/home/gian/music/miles_davis_featuring_keith_jarrett/what_i_say_volume_1/03_what_i_say.flac
/home/gian/music/miles_davis_featuring_keith_jarrett/what_i_say_volume_1/04_sanctuary.flac
/home/gian/music/miles_davis_featuring_keith_jarrett/what_i_say_volume_1/05_ita_tm_s_about_that_time.flac
/home/gian/music/tomaso_giovanni_albinoni,_johann_pachelbel,_johann_sebastian_bach,_george_frideric_handel,_antonio_vivaldi,_henry_purcell_orpheus_chamber_orchestra/albinoni_adagio_pachelbel_canon/01_canon_in_d_major_for_strings_and_basso_continuo.m4a
/home/gian/music/tomaso_giovanni_albinoni,_johann_pachelbel,_johann_sebastian_bach,_george_frideric_handel,_antonio_vivaldi,_henry_purcell_orpheus_chamber_orchestra/albinoni_adagio_pachelbel_canon/02_adagio_in_g_minor_for_strings_and_organ.m4a
/home/gian/music/tomaso_giovanni_albinoni,_johann_pachelbel,_johann_sebastian_bach,_george_frideric_handel,_antonio_vivaldi,_henry_purcell_orpheus_chamber_orchestra/albinoni_adagio_pachelbel_canon/03_a_oejesu,_joy_of_man_s_desiringa_chorale_from_a_oeherz_und_mund_und_tat_und_lebena_bwv_147-johann_sebastian_bach.m4a
/home/gian/music/tomaso_giovanni_albinoni,_johann_pachelbel,_johann_sebastian_bach,_george_frideric_handel,_antonio_vivaldi,_henry_purcell_orpheus_chamber_orchestra/albinoni_adagio_pachelbel_canon/04_chacony_in_g_minor_for_strings_and_basso_continuo.m4a
/home/gian/music/tomaso_giovanni_albinoni,_johann_pachelbel,_johann_sebastian_bach,_george_frideric_handel,_antonio_vivaldi,_henry_purcell_orpheus_chamber_orchestra/albinoni_adagio_pachelbel_canon/05_orchestral_suite_no._3_in_d_major,_bwv_1068_air.m4a
/home/gian/music/tomaso_giovanni_albinoni,_johann_pachelbel,_johann_sebastian_bach,_george_frideric_handel,_antonio_vivaldi,_henry_purcell_orpheus_chamber_orchestra/albinoni_adagio_pachelbel_canon/06_concerto_in_g_minor-a_oechristmas_concertoa-,_op._6_no._8_1._vivace_a_grave.m4a
/home/gian/music/tomaso_giovanni_albinoni,_johann_pachelbel,_johann_sebastian_bach,_george_frideric_handel,_antonio_vivaldi,_henry_purcell_orpheus_chamber_orchestra/albinoni_adagio_pachelbel_canon/07_concerto_in_g_minor-a_oechristmas_concertoa-,_op._6_no._8_2._allegro.m4a
/home/gian/music/tomaso_giovanni_albinoni,_johann_pachelbel,_johann_sebastian_bach,_george_frideric_handel,_antonio_vivaldi,_henry_purcell_orpheus_chamber_orchestra/albinoni_adagio_pachelbel_canon/08_concerto_in_g_minor-a_oechristmas_concertoa-,_op._6_no._8_3._adagio_a_allegro_a_adagio.m4a
/home/gian/music/tomaso_giovanni_albinoni,_johann_pachelbel,_johann_sebastian_bach,_george_frideric_handel,_antonio_vivaldi,_henry_purcell_orpheus_chamber_orchestra/albinoni_adagio_pachelbel_canon/09_concerto_in_g_minor-a_oechristmas_concertoa-,_op._6_no._8_4._vivace.m4a
/home/gian/music/tomaso_giovanni_albinoni,_johann_pachelbel,_johann_sebastian_bach,_george_frideric_handel,_antonio_vivaldi,_henry_purcell_orpheus_chamber_orchestra/albinoni_adagio_pachelbel_canon/10_concerto_in_g_minor-a_oechristmas_concertoa-,_op._6_no._8_5._allegro_6._pastorale_largo.m4a
/home/gian/music/tomaso_giovanni_albinoni,_johann_pachelbel,_johann_sebastian_bach,_george_frideric_handel,_antonio_vivaldi,_henry_purcell_orpheus_chamber_orchestra/albinoni_adagio_pachelbel_canon/11_solomon_act_iii_sinfonia_in_b_flat_major_a_oethe_arrival_of_the_queen_of_shebaa_allegro.m4a
/home/gian/music/tomaso_giovanni_albinoni,_johann_pachelbel,_johann_sebastian_bach,_george_frideric_handel,_antonio_vivaldi,_henry_purcell_orpheus_chamber_orchestra/albinoni_adagio_pachelbel_canon/12_xerxes_act_i_largo_in_f_major.m4a
/home/gian/music/tomaso_giovanni_albinoni,_johann_pachelbel,_johann_sebastian_bach,_george_frideric_handel,_antonio_vivaldi,_henry_purcell_orpheus_chamber_orchestra/albinoni_adagio_pachelbel_canon/13_concerto_for_4_violins_in_b_minor,_op._3_no._10_1._allegro.m4a
/home/gian/music/tomaso_giovanni_albinoni,_johann_pachelbel,_johann_sebastian_bach,_george_frideric_handel,_antonio_vivaldi,_henry_purcell_orpheus_chamber_orchestra/albinoni_adagio_pachelbel_canon/14_concerto_for_4_violins_in_b_minor,_op._3_no._10_2._largo.m4a
/home/gian/music/tomaso_giovanni_albinoni,_johann_pachelbel,_johann_sebastian_bach,_george_frideric_handel,_antonio_vivaldi,_henry_purcell_orpheus_chamber_orchestra/albinoni_adagio_pachelbel_canon/15_concerto_for_4_violins_in_b_minor,_op._3_no._10_3._allegro.m4a
/home/gian/music/wolfgang_amadeus_mozart/requiem/01_requiem_aeternam-eternal_rest-.mp3
/home/gian/music/wolfgang_amadeus_mozart/requiem/02_kyrie_eleison-lord_have_mercy-.mp3
/home/gian/music/wolfgang_amadeus_mozart/requiem/03_dis_irae-day_of_wrath-.mp3
/home/gian/music/wolfgang_amadeus_mozart/requiem/04_tuba_mirum-the_trumpet_mighty_blast-.mp3
/home/gian/music/wolfgang_amadeus_mozart/requiem/05_rex_tremendae_majestatis-king_of_fearful_majesty-.mp3
/home/gian/music/wolfgang_amadeus_mozart/requiem/06_recordare,_jesu_pie-remembering_loving_jesus-.mp3
/home/gian/music/wolfgang_amadeus_mozart/requiem/07_confutatis_maledictis-when_sentence_on_the_damned-.mp3
/home/gian/music/wolfgang_amadeus_mozart/requiem/08_lacrymosa-a_day_of_tears-.mp3
/home/gian/music/wolfgang_amadeus_mozart/requiem/09_domine_jesu_christe-o_lord_jesus_christ-.mp3
/home/gian/music/wolfgang_amadeus_mozart/requiem/10_hostias-sacrifices-.mp3
/home/gian/music/wolfgang_amadeus_mozart/requiem/11_sanctus-holy,_holy,_holy-.mp3
/home/gian/music/wolfgang_amadeus_mozart/requiem/12_benedictus-blessed-.mp3
/home/gian/music/wolfgang_amadeus_mozart/requiem/13_agnus_dei-lamb_of_god-.mp3
/home/gian/music/wolfgang_amadeus_mozart/requiem/14_lux_aeterna-peripheral_light-.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/01_symphony_no._40_in_g_minor_k550_i._molto_allegro.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/02_clarinet_concerto_in_a_k622_ii._adagio.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/03_symphony_no._25_in_g_minor_k183_i._allegro-opening-.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/04_piano_concerto_no._21_in_c_k467_ii._andante.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/05_symphony_no._35_in_d_k385_haffner_iv._finale._presto.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/06_violin_concerto_no._3_in_g_k216_ii._adagio.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/07_divertimento_in_d_k334_iii._menuetto-trio.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/08_symphony_no._41_in_c_k551_jupiter_iv._allegro.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/09_piano_concerto_no._23_in_a_k488_ii._adagio.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/10_horn_concerto_no._4_in_e-flat_k495_iii._rondo._allegro_vivace.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/11_concerto_for_flute_and_harp_in_c_k299_ii_andantino.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/12_sinfonia_concertante_for_violin,_viola_and_orchestra_in_e_flat_k364_iii._presto.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/13_le_nozze_di_figaro_k492_overture.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/14_le_nozze_di_figaro_k492_non_pia1_andrai-figaro-.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/15_le_nozze_di_figaro_k492_porgi_amor-countess-.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/16_le_nozze_di_figaro_k492_voi_che_sapete-cherubino-.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/17_le_nozze_di_figaro_k492_hai_gia_vinta_la_causa_..._vedra2_mentr_io_sospiro-count-.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/18_le_nozze_di_figaro_k492_dove_sono-countess-.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/19_le_nozze_di_figaro_k492_canzonetta_sull_aria..._che_soave_zefiretto-countess_and_susanna-.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/20_le_nozze_di_figaro_k492_deh_vieni,_non_tardar-susanna-.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/21_cosi_fan_tutte_k588_bella_vita_militar-chorus-.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/22_cosi_fan_tutte_k588_soave_sia_il_vento-fiordiligi,_dorabella_and_don_alfonso-.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/23_cosi_fan_tutte_k588_smanie_implacabili-dorabella-.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/24_cosi_fan_tutte_k588_l_intatta_fede...come_scoglio-fiordiligi-.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/25_cosi_fan_tutte_k588_un_aura_amorosa-ferrando-.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/26_don_giovanni_k527_madamina,_il_catalogo_a_questo-leporello-.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/27_don_giovanni_k527_la_ci_darem_la_mano-don_giovanni_and_zerlina-.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/28_don_giovanni_k527_or_sai_chi_l_onore-donna_anna-.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/29_don_giovanni_k527_dalla_sua_pace-don_ottavio-.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/30_don_giovanni_k527_finch_han_dal_vino-don_giovanni-.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/31_don_giovanni_k527_deh,_vieni_alla_finestra-don_giovanni-.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/32_don_giovanni_k527_vedrai,_carino-zerlina-.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/33_don_giovanni_k527_in_quali_eccessi,_o_numi..._mi_tradi,_quell_alma_ingrata-donna_elvira-.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/34_don_giovanni_k527_questo_a_il_fin-ensemble-.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/35_der_schauspieldirektor_k486_overture.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/36_idomeneo_k366_fuor_del_mar_ho_un_mar_in_seno-idomeneo-.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/37_idomeneo_k366_zeffiretti_lusinghieri-ilia-.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/38_die_entfa_hrung_aus_dem_serail_k384_konstanze,_dich_wieder_zu_sehen,_dich-belmonte-.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/39_die_entfa_hrung_aus_dem_serail_k384_martern_aller_arten-konstanze-.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/40_die_entfa_hrung_aus_dem_serail_k384_welche_wonne,_welche_lust-blonde-.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/41_die_entfa_hrung_aus_dem_serail_k384_vivat_bacchus-osmin_and_pedrillo-.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/42_die_entfa_hrung_aus_dem_serail_k384_o,_wie_will_ich_triumphieren-osmin-.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/43_die_zauberfla_pp_te_k620_overture.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/44_die_zauberfla_pp_te_k620_der_vogelfa_nger_bin_ich_ja-papageno-.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/45_die_zauberfla_pp_te_k620_dies_bildnis_ist_bezaubernd_scha_pp_n-tamino-.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/46_die_zauberfla_pp_te_k620_bei_ma_nnern-pamina_and_papageno-.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/47_die_zauberfla_pp_te_k620_schnelle_fa_aye-pamina,_papageno_and_monostatos-.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/48_die_zauberfla_pp_te_k620_o_isis_und_osiris-sarastro_and_chorus-.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/49_die_zauberfla_pp_te_k620_der_ha_pp_lle_rache-queen_of_night-.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/50_die_zauberfla_pp_te_k620_ach,_ich_fa_hl_s-pamina-.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/51_die_zauberfla_pp_te_k620_ein_ma_dchen_oder_weibchen-papageno-.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/52_die_zauberfla_pp_te_k620_pa-pa-pa-pa-papagena-papagena_and_papageno-.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/53_o_du_eselhafter_martin_k560.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/54_bona_nox,_bist_a_rechta_ox_k561.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/55_essen_und_trinken_k234.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/56_piano_sonata_in_a_minor_k331_iii._rondo_alla_turca._allegretto.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/57_serenade_in_b_flat_k361_gran_partita_iii._adagio.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/58_das_butterbrot.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/59_violin_sonata_in_e_minor_k304_i._allegro.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/60_ah_vous_dirais-je_maman_in_c_k265.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/61_serenade_in_g_k525_eine_kleine_nachtmusik_i._allegro.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/62_serenade_in_g_k525_eine_kleine_nachtmusik_ii._romance._andante.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/63_serenade_in_g_k525_eine_kleine_nachtmusik_iii._minuetto._allegretto_and_trio.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/64_serenade_in_g_k525_eine_kleine_nachtmusik_iv._rondo._allegro.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/65_die_schlittenfahrt_k605_no.3.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/66_fantasia_in_d_minor_k397.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/67_divertimento_for_string_trio_in_e_flat_k563_vi._finale._allegro.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/68_masonic_funeral_music_k477.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/69_piano_sonata_in_c_k545_i._allegro.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/70_piano_sonata_in_c_k545_ii._andante.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/71_piano_sonata_in_c_k545_iii._allegro.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/72_sonata_for_two_pianos_in_d_k448_i._allegro_con_spirito.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/73_clarinet_quintet_in_a_k581_ii._larghetto.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/74_serenade_for_winds_in_c_minor_k388_iii._menuetto_in_canone.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/75_flute_quartet_in_g_k285a_i._andante.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/76_quintet_for_piano,_oboe,_clarinet,_horn_and_bassoon_in_e_flat_k452_iii._rondo._allegretto.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/77_duo_for_violin_and_viola_in_g_k423_ii._adagio.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/78_piano_sonata_in_a_minor_k310_iii._presto.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/79_string_quartet_in_b_flat_k458_hunt_iv._allegro_assai.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/80_oboe_quartet_in_f_k370_iii._rondo._allegro.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/81_piano_concerto_no.26_in_d_k537_coronation_ii._adagio.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/82_violin_concerto_no.5_in_a_k219_iii._rondeau._tempo_di_minuetto.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/83_menuet_in_d_k355.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/84_serenade_for_wind_instruments_in_e_flat_k375_v._finale._allegro.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/85_ein_musikalischer_spaay_in_f_k522_i._allegro.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/86_ein_musikalischer_spaay_in_f_k522_iv._presto.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/87_requiem_in_d_minor_k626_introit._requiem_aeternam.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/88_requiem_in_d_minor_k626_kyrie.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/89_requiem_in_d_minor_k626_lacrimosa.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/90_vesperae_solennes_de_confessore_k339_laudate_dominum.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/91_ave_verum_corpus_k618.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/92_litaniae_lauretanae_k195_agnus_dei.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/93_mass_in_c_minor_k427_et_incarnatus_est.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/94_mass_in_c_major_k317_coronation_benedictus.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/95_exsultate,_jubilate_k165.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/96_regina_coeli_k127_regina_coeli.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/97_sancta_maria,_mater_dei_k273.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/98_betracht_dies_herz_k42.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/99_an_die_freundschaft_k125h.mp3
/home/gian/music/wolfgang_amadeus_mozart/best_mozart_100/100_die_zauberfla_pp_te.mp3
/home/gian/music/wolfgang_amadeus_mozart/the_very_best_of_mozart/01 Serenade No. 13 in G major, K. 525 _Eine kleine Nachtmusik__ I. Allegro.mp3
/home/gian/music/wolfgang_amadeus_mozart/the_very_best_of_mozart/02 Horn Concerto No. 3 in E-flat major, K. 447_ III. Allegro.mp3
/home/gian/music/wolfgang_amadeus_mozart/the_very_best_of_mozart/03 Cosi fan tutte, K. 588, Act I_ Soave sia il vento.mp3
/home/gian/music/wolfgang_amadeus_mozart/the_very_best_of_mozart/04 Violin Sonata No. 26 in B-flat major, K. 378_ II. Andantino sostenuto e cantabile.mp3
/home/gian/music/wolfgang_amadeus_mozart/the_very_best_of_mozart/05 Requiem in D minor, K. 626_ Confutatis maledictis - Lacrimosa dies illa.mp3
/home/gian/music/wolfgang_amadeus_mozart/the_very_best_of_mozart/06 Symphony No. 40 in G minor, K. 550_ I. Molto allegro.mp3
/home/gian/music/wolfgang_amadeus_mozart/the_very_best_of_mozart/07 String Quartet No. 17 in B-flat major, K. 458, _Hunt__ Minuetto.mp3
/home/gian/music/wolfgang_amadeus_mozart/the_very_best_of_mozart/08 Don Giovanni, K. 527, Act I_ La ci darem la mano.mp3
/home/gian/music/wolfgang_amadeus_mozart/the_very_best_of_mozart/09 3 German Dances, K. 605_ German Dance, No. 3, K. 605, _Sleigh Ride_.mp3
/home/gian/music/wolfgang_amadeus_mozart/the_very_best_of_mozart/10 Piano Concerto No. 20 in D minor, K. 466_ III. Allegro assai.mp3
/home/gian/music/wolfgang_amadeus_mozart/the_very_best_of_mozart/11 Le nozze di Figaro, K. 492, Act II_ Voi, che sapete.mp3
/home/gian/music/wolfgang_amadeus_mozart/the_very_best_of_mozart/12 Symphony No. 25 in G minor, K. 183_ I. Allegro con brio.mp3
/home/gian/music/wolfgang_amadeus_mozart/the_very_best_of_mozart/13 Ave verum corpus in D major, K. 618.mp3
/home/gian/music/wolfgang_amadeus_mozart/the_very_best_of_mozart/14 Le nozze di Figaro, K. 492, Act I_ Overture.mp3
/home/gian/music/wolfgang_amadeus_mozart/the_very_best_of_mozart/15 Clarinet Concerto in A major, K. 622_ II. Adagio.mp3
/home/gian/music/wolfgang_amadeus_mozart/the_very_best_of_mozart/16 Mass No. 18 in C minor, K. 427, _Great__ Kyrie.mp3
/home/gian/music/wolfgang_amadeus_mozart/the_very_best_of_mozart/17 Piano Concerto No. 21 in C major, K. 467 _Elvira Madigan__ II. Andante.mp3
/home/gian/music/wolfgang_amadeus_mozart/the_very_best_of_mozart/18 Symphony No. 41 in C major, K. 551 _Jupiter__ IV. Molto allegro.mp3
/home/gian/music/wolfgang_amadeus_mozart/the_very_best_of_mozart/19 Die Zauberflöte, K. 620, Act II_ Der Hölle Rache, _Queen of the Night_.mp3
/home/gian/music/wolfgang_amadeus_mozart/the_very_best_of_mozart/20 Piano Sonata No. 11 in A major, K. 331_ III. Rondo alla turca.mp3
/home/gian/music/wolfgang_amadeus_mozart/the_very_best_of_mozart/21 Concerto for Flute and Harp in C major, K. 299_ II. Andantino.mp3
/home/gian/music/wolfgang_amadeus_mozart/the_very_best_of_mozart/22 Serenade No. 10 in B-flat major, K. 361, _Gran Partita__ III. Menuetto.mp3
/home/gian/music/wolfgang_amadeus_mozart/the_very_best_of_mozart/23 Clarinet Quintet in A major, K. 581_ II. Larghetto.mp3
/home/gian/music/wolfgang_amadeus_mozart/the_very_best_of_mozart/24 Violin Concerto No. 5 in A major, K. 219 _Turkish__ III. Rondo. Tempo di minuetto.mp3
