#! /bin/sh

setWorkspaces.sh
sxhkd -c $HOME/.config/sxhkd/bspwm_sxhkd &

bspc config border_width         1
bspc config window_gap           0
bspc config automatic_scheme     spiral
bspc config split_ratio          0.5
# bspc config borderless_monocle   true
# bspc config gapless_monocle      true
# bspc config leaf_monocle	 true
# bspc config single_monocle	 true
bspc rule -a '*:zathura'                  state=tiled
bspc config focus_follows_pointer true
# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color0"
bspc config active_border_color "$color0"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

# X cursor
xsetroot -cursor_name left_ptr &

bspwmbar
