#!/bin/sh

alias v="nvim" \
	g="git" \
	ls="ls --color=auto" \
	mg="nvim -c MagitOnly" \
	pa="pulsemixer" \
	news="newsboat -u $HOME/.local/share/newsboat/urls" \
	bat="cat /sys/class/power_supply/BAT0/capacity" \
	stx="starttmux" \
	ms="starttmux music cmus" \
	ww="starttmux web 'w3m -v'" \
	cal="starttmux calendar calcurse" \
	m="starttmux matlab 'lf $REPOS/matlab'" \
	wk="nvim -c VimwikiIndex" \
	cg="checkstatusgit --dmenu" \
	gp="git push origin" \
	scim="sc-im" \
	kl="killall"


