#!/bin/sh

# List of aliases

alias v="nvim" \
	g="git" \
	in="task add +inbox" \
	tt="task -inbox -someday" \
	ti="task inbox" \
	install="sudo apt-get install" \
	p="sudo pacman" \
	cre="crontab -e" \
	mg="nvim -c MagitOnly" \
	tw="nvim -c TW" \
	wd="nvim -c VimwikiMakeDiaryNote" \
	wal="wal --vte" \
	z='zathura' \
	SS='sudo systemctl' \
	ls='ls --color=auto' \
	duck='sr duckduckgo' \
	pirate='pirate-get -t' \
	cal='calcurse -D ~/.config/calcurse' \
	gp='git push origin master' \
	f='vifmrun' \
	tra="transmission-remote-cli" \
	pp="pip3 install --user" \
	kl="killall" \
	scim="sc-im" \
	z="zathura" \
	f="vifmrun.sh" \
	yt="yt.sh -v" \
	yta="yt.sh -a" \
	ytp="yt.sh -p" \
	cal="calcurse -D $HOME/.config/calcurse" \
	app="sc-im $HOME/repos/debian-installer/debian-apps.csv" \
	stw="stow -vt ~" \
	bs="bookmark.sh"





fs() { ls $HOME/.local/bin/*/* | grep -v '__' | fzf | xargs $EDITOR ;}
ff() { cat $HOME/.config/shortcuts/files | fzf | xargs -r -I % $EDITOR % ;}
fd() {
	dir=$(cat $HOME/.config/shortcuts/directories | fzf)
	cd $dir && ls -a ;}
