#!/bin/sh

# List of aliases

alias v="nvim" \
	g="git" \
	in="task add +inbox" \
	tt="task -inbox -someday" \
	ti="task inbox" \
	install="sudo apt-get install" \
	p="sudo pacman" \
	cre="crontab -e" \
	mg="nvim -c MagitOnly" \
	tw="nvim -c TW" \
	wd="nvim -c VimwikiMakeDiaryNote" \
	wal="wal --vte" \
	z='zathura' \
	SS='sudo systemctl' \
	ls='ls --color=auto' \
	duck='sr duckduckgo' \
	pirate='pirate-get -t' \
	cal='calcurse -D ~/.config/calcurse' \
	gp='git push origin master' \
	f='vifmrun' \
	tra="transmission-remote-cli" \
	pp="pip3 install --user" \
	kl="killall" \
	scim="sc-im" \
	z="zathura" \
	YT="youtube-viewer" \
	f="vifmrun" \
	yt="yt.sh -v" \
	yta="yt.sh -a" \
	ytp="yt.sh -p" \
	cal="calcurse -D $HOME/.config/calcurse" \
	app="sc-im $HOME/repos/setup/installer/apps/laptop.csv" \
	x="sxiv -ft *" \
	bs="bookmark.sh" \
	guu="git update-index --assume-unchanged" \
	grr="git rm --cached" \
	vitw="vit +@internet" \
	upd="yay -Syu" \
	sss="ssh gian@gianlucatadori.xyz" \
	install="sudo apt-get install" \
	mtl="ptb3-matlab -nodesktop -nosplash" \
	jw="nvim -c VimwikiMakeDiaryNote" \
	abok="abook -C $HOME/.config/abook/abookrc --datafile $HOME/.config/abook/addressbook" \
	w3m="w3m -config $HOME/.config/w3m/config -v"

fs() { du -a $HOME/.local/bin/**/* $HOME/.config/ $HOME/.xprofile $HOME/.xinitrc $HOME/.profile $HOME/.tmux.conf | awk '{print $2}' | fzf | xargs -r $EDITOR ;}

