#**********************************************/
#* ██████╗ ███████╗███████╗████████╗███████╗  */
#* ██╔══██╗██╔════╝██╔════╝╚══██╔══╝██╔════╝  */
#* ██████╔╝█████╗  █████╗     ██║   ███████╗  */
#* ██╔══██╗██╔══╝  ██╔══╝     ██║   ╚════██║  */
#* ██████╔╝███████╗███████╗   ██║   ███████║  */
#* ╚═════╝ ╚══════╝╚══════╝   ╚═╝   ╚══════╝  */
#*                                            */
#**********************************************/


directory: ~/media/Music
library: ~/.config/beets/musiclibrary.db
import:
    move: yes
plugins: lyrics lastgenre edit
